sudo: required
services:
  - docker

before_install:
  - docker build -t basanop/multi-container -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true basanop/multi-container npm run test

after_success:
  - docker build -t basanop/multi-client ./client
  - docker build -t basanop/multi-nginx ./nginx
  - docker build -t basanop/multi-server ./server
  - docker build -t basanop/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push basanop/multi-client
  - docker push basanop/multi-nginx
  - docker push basanop/multi-server
  - docker push basanop/multi-worker
